### PR TITLE
Catayoyo

### PR DESCRIPTION
**Pull request by catayoyo**
Hello,

I believe this has all been successful now. Fingers crossed!

Thanks for all the help,
Amelia

### CODE REVIEW

**Comment by stdlibdoh** [comment]
Right so I've been able to run FizzBuzz and TowersOfHanoi with ease. They perform as expected which is great! However, I think you might've missed a few things with SudokuSolver. Error is:

```
Sudoku.java:27: error: cannot find symbol
    return !isInRow(row,number) && !isInCol(col,number) && !isInBox(row,col,number);
                                                            ^
  symbol:   method isInBox(int,int,int)
  location: class Sudoku
1 error
```

Can't seem to be able to fid the isInBox method so I'm just assuming it got clipped out maybe. Can you try to fix that and pushing again?

Any issues that you may encounter, be it with Java (and running your code) or with Git and GitHub, just create a new issue.

**Comment by catayoyo** [comment]
That may be because myself and Diana originally wrote it on IntelliJ using a Main class and SudokuSolver class and the platform doesn't let me add a new class so I had to try and merge it a bit. I'll see if I can work out how to fix it.

**Comment by stdlibdoh** [comment]
That missing function is now fixed. There's just two more issues to fix until it is done:

1. Hint: You're instantiating an object of type Sudoku by giving it a 2D array. Maybe the Sudoku constructor is missing something?
```
MainSudoku.java:17: error: incompatible types: int[][] cannot be converted to int[]
        Sudoku sudoku = new Sudoku(GRID_TO_SOLVE);
```

2. 
```
Sudoku grid to solve
 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0
```
This is what happens when you run the code. You're already have a variable named GRID_TO_SOLVE that is used by the constructor but, when you're running the ```display``` method, the 2D array appears to be empty. Again, maybe the constructor is missing something

**Comment by stdlibdoh** [comment]
You are so close! Just a few more things to iron out:

1. The error wasn't fixed. You're instantiating a new object of type ```Sudoku``` by calling the constructor with a 2D array, defined as ```int[][] GRID_TO_SOLVE```. However the defined Sudoku constructor is:
```
public Sudoku(int[] board) {
    // some code
}
```
Can you see where the error is?

2. You've clearly identified the error in the ```table``` variable being simply initialised as an empty 2D array. However, running the code throws:
```
SudokuSolver.java:42: error: cannot find symbol
        this.board[i][j] = GRID_TO_SOLVE[i][j];
```
Hint: ```GRID_TO_SOLVE``` is declared in class ```Main```. Even though it is public, it has to be properly referenced to be able to be used in a different class. You are, however, calling the constructor to class ```Sudoku``` and giving it a "temporary name" of ```board```. Remember that in the constructor, ```this.table``` is different from ```table```.

**Comment by stdlibdoh** [comment]
Just a few notes that might've escaped me.

You can and should test your code and you can do that using the built in terminal. There's only two commands you need to know: ```javac``` and ```java```.

* To compile your code, navigate to where your file is, by typing ```cd <path_name>``` in the terminal. In your case, it should be ```cd catayoyo-sprint-1/answers/catayoyo``` followed by whichever folder you want to get into.

* Once there, youll be running ```javac``` to compile and ```java``` to run. An example would be:
    * ```javac FizzBuss.java```
    * ```java FizzBuzz```

Notice that ```java``` takes a .java file and ```java``` just takes the file without the .java.

* While this will work for FizzBuzz and TowersOfHanoi, it won't work for SudokuSolver as there's two main classes inside the same file. You can split these up into two different .java files. For instance, you could have a SudokuTest.java and a Sudoku.java. 

* While splitting these up, the only thing to take into consideration is naming. So if, in your code, you have a ```public class Main```, your java would be named ```Main.java```. Same for ```public class Sudoku```.

* In compiling and running these files, remember their order. Your Main class is calling your Sudoku class so compiling and running Main is sufficient

PS: Apologies if I didn't mention it any sooner. These assignments were designed with pair-programming in mind and it is unfortunate that you're doing them by yourself. You are still doing amazing so keep at it 💪

**Comment by catayoyo** [comment]
Hi Wilson,

I called Diana on Skype to ask her for help as I wasn’t sure what you meant and it worked in IntelliJ, but again, I had the classes on two different class files instead of on the same one and I think that’s where it’s failing. In the intelliJ version I imported the static version to the sudoku class but I can’t seem to do it properly on the internal ide (or at least I don’t know how to do so). 

I’m not used to commands at all, so normally I’d just right click and create a new class from the menu, and running it I would just click the play button so knowing I have to use commands to do that is a big help.

Sadly I’m in London all day tomorrow so I’ll have to get back to this on Thursday.

Thanks for your support today!

**Comment by stdlibdoh** [comment]
Hi Amelia,

I know exactly what you mean: for a while I used IntelliJ as my Java IDE, but for several reasons, ended up swapping it for VisualStudio Code.

Not a problem. Now that I know, we can hack our way through the rest of it on Thursday 😄 

Have a lovely Wednesday!

**Comment by catayoyo** [comment]
Ok I did fix this but my commit isn't going through and if I try to push after that I get this error now:

` ! [rejected]        catayoyo -> catayoyo (non-fast-forward)`
`error: failed to push some refs to 'https://github.com/catayoyo/fb-sprint-1''`
`hint: Updates were rejected because the tip of your current branch is behind`
`hint: its remote counterpart. Integrate the remote changes (e.g.`
`hint: 'git pull ...') before pushing again.`
`hint: See the 'Note about fast-forwards' in 'git push --help' for details.`

**Comment by stdlibdoh** [comment]
Hi,

Few things come to mind:

* Make sure you pushing to the right repo: that will be under your own account, so catayoyo/fb-sprint-1. Also make sure you're working in the right branch, refer to previous instructions on how to check what your current branch is. For instructions on how to check where you're pushing and pulling from, read the documentations provided under Sprint 1. If you can't find it, ping it and I'll write more detailed instructions.

* There has been a merge in the underland/fb-sprint-1 repo. I don't believe this impacts you in any way as you'll be submitting a PR from your repo to this one. 

* It also may be an issue you can resolve by just further Googling. These aren't meant to be tutorials to be followed step by step but rather a collaborative approach: Look up documentation, google your issue, talk to the other students and hopefully you'll be able to solve them. 

Apologies if I'm being more cryptic in this answer than I was before but there is significant knowledge to be gained if you face issues and solve them by yourself. I do understand the frustration of hitting walls and not being able to solve them straight away but unfortunately (or maybe not), that is the life of a software developer 💪 !

**Comment by stdlibdoh** [comment]
I'm sorry you were unable to fix it, you were so close. In the Sudoku constructor, you initialised board to be a single, rather than a 2D array.

You could then do a straight assignment between ```board``` and ```this.board```.

```java
public Sudoku(int[][] board) {
        this.board = board;
}
```

Closing as issue wasn't fixed

**Pull request closed without merging**
